languageCode = "en-us"
title = "Maltob"
baseURL = "/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
<<<<<<< HEAD

[params]
favicon = "favicon-16x16.png"
=======
 
[params]
favicon = "favicon.png"
>>>>>>> c76d13aef1ffd588ca4e51f091a847c2308dbe42
