languageCode = "en-us"
title = "Maltob"
baseURL = "/"
theme = "hugo-theme-massively"
googleanalytics = "UA-142195063-1"
disqusShortname = ""

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = true
 
[languages]
[languages.en]
  languageName = "English"

[params]
favicon = "icone/favicon.ico"
dateFormat = "02.01.2006"

[params.posts]
     folderName = "post"
     pageSize = "6"
     featuredPost = "true"
     paginationPages = 2
     showFirstLast = true
